version: "3.3"
services:
  myspeed:
    expose:
      - 5216
    volumes:
      - /mnt/data/myspeed:/myspeed/data
    restart: unless-stopped
    image: germannewsmaker/myspeed:1.0.9
    networks:
      - traefik_proxynetwork
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.myspeed.rule=Host(`myspeed.cosmos.cboxlab.com`)"
    - "traefik.http.routers.myspeed.entrypoints=websecure"
    - "traefik.http.routers.myspeed.tls=true"
    - "traefik.http.routers.myspeed.tls.certresolver=letsencrypt"
    - "traefik.http.routers.myspeed.tls.domains[0].main=cosmos.cboxlab.com"
    - "traefik.http.routers.myspeed.tls.domains[0].sans=*.cosmos.cboxlab.com"
networks:
  traefik_proxynetwork:
    external: true
