name: speedtest
services:
  speedtest:
    restart: unless-stopped
    container_name: openspeedtest
    image: openspeedtest/latest   
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.speedtest.rule=Host(`speedtest-nas.cosmos.cboxlab.com`)"
    - "traefik.http.routers.speedtest.entrypoints=websecure"
    - "traefik.http.routers.speedtest.tls=true"
    - "traefik.http.routers.speedtest.tls.certresolver=letsencrypt"
    - "traefik.http.routers.speedtest.tls.domains[0].main=cosmos.cboxlab.com"
    - "traefik.http.routers.speedtest.tls.domains[0].sans=*.cosmos.cboxlab.com"
    networks:
      - traefik_proxynetwork

networks:
  traefik_proxynetwork:
    external: true
