name: speedtest
services:
  speedtest:
    restart: unless-stopped
    container_name: openspeedtest
    image: openspeedtest/latest   
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.speedtest.rule=Host(`speedtest.cosmos.cboxlab.com`)"
    - "traefik.http.routers.speedtest.entrypoints=web"
    networks:
      - traefik_proxynetwork

networks:
  traefik_proxynetwork:
    external: true
