name: traefik
services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    command:
      - --log
      - --log.level=INFO
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      # - --entrypoints.websecure.http.tls=true
      #- --entrypoints.websecure.http.tls.certresolver=letsencrypt
    ports:
      - 80:80
      - 8443:443 # Switch to 443 later
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik_proxynetwork
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.cosmos.cboxlab.com`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      #- "traefik.http.routers.traefik.tls=true"
      
networks:
  traefik_proxynetwork:
    name: traefik_proxynetwork
