name: immich
services:
  redis:
    container_name: immich_redis
    image: docker.io/redis:7.4.1-alpine3.20
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.135.3
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.135.3
    volumes:
      - /mnt/immich:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - .env
    depends_on:
      - redis
    restart: always
    networks:
      - traefik_proxynetwork
      - default
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.immich.rule=Host(`immich.cosmos.cboxlab.com`)"
    - "traefik.http.routers.immich.entrypoints=websecure"
    - "traefik.http.routers.immich.tls=true"
    - "traefik.http.routers.immich.tls.certresolver=letsencrypt"
    - "traefik.http.routers.immich.tls.domains[0].main=cosmos.cboxlab.com"
    - "traefik.http.routers.immich.tls.domains[0].sans=*.cosmos.cboxlab.com"
    - "traefik.http.services.immich.loadbalancer.server.port=2283"
volumes:
  model-cache: null
networks:
  traefik_proxynetwork:
    external: true
