version: "3"
services:
  minio:
    image: docker.io/bitnami/minio:2025.3.12
    expose:
      - 9000
      - 9001
    volumes:
      - /mnt/data/minio/:/bitnami/minio/data
    restart: unless-stopped
    networks:
      - nginx_proxynetwork
      - traefik_proxynetwork
    env_file: .env
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.minio.rule=Host(`minio.cosmos.cboxlab.com`)"
    - "traefik.http.routers.minio.entrypoints=websecure"
    - "traefik.http.services.minio.loadbalancer.server.port=9000"
    - "traefik.http.routers.minio-admin.rule=Host(`minio-admin.cosmos.cboxlab.com`)"
    - "traefik.http.routers.minio-admin.entrypoints=websecure"
    - "traefik.http.services.minio-admin.loadbalancer.server.port=9001"
networks:
  nginx_proxynetwork:
    external: true
  traefik_proxynetwork:
    external: true
