
services:
  copyparty:
    image: copyparty/ac:1.18.9
    container_name: copyparty
    user: "1000:1000"
    volumes:
      - ./cfg:/cfg:z
      - /mnt/data/copyparty:/w/shared:z
    networks:
      - traefik_proxynetwork
    expose:
      - 3923
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.copyparty.rule=Host(`files.cosmos.cboxlab.com`)"
      - "traefik.http.routers.copyparty.entrypoints=websecure"
      - "traefik.http.routers.copyparty.tls=true"
      - "traefik.http.services.copyparty.loadbalancer.server.port=3923"
      - "traefik.http.routers.copyparty.tls.certresolver=letsencrypt"
      - "traefik.http.routers.copyparty.tls.domains[0].main=cosmos.cboxlab.com"
      - "traefik.http.routers.copyparty.tls.domains[0].sans=*.cosmos.cboxlab.com"
    stop_grace_period: 15s
    environment:
      PYTHONUNBUFFERED: 1

networks:
  traefik_proxynetwork:
    external: true
