version: "3.8"
services:
  app:
    image: jc21/nginx-proxy-manager:2.12.3
    restart: unless-stopped
    ports:
      - 81:81
      - 443:443
    volumes:
      - /mnt/data/nginx/data:/data
      - /mnt/data/nginx/letsencrypt:/etc/letsencrypt
    environment:
      PUID: 1000
      PGID: 3000
      DISABLE_IPV6: "true"
      S6_STAGE2_HOOK: sed -i $$d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh # https://github.com/truenas/charts/issues/1212
    networks:
      - nginx_proxynetwork
networks:
  nginx_proxynetwork:
    name: nginx_proxynetwork
